### ISSUE TITLE
CSV previews contain assets from whitehall-admin

### ISSUE THREAD

**Issue by alexmuller** [alphagov/whitehall#2345] opened 2015-09-22 18:21 UTC
This public page: https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/387271/exrates-201411.csv/preview

Contains this code:

```
<link rel="stylesheet" media="screen" href="//whitehall-admin.production.alphagov.co.uk/government/assets/frontend/html-publication-e0b258a6f964fbcace322634a69d92a503dc26ee7ef8ca5e5133266da3f221d8.css">
```

Which is not correct.

**Comment by ajlanghorn** [comment] 2015-09-23 07:33
@alexmuller I can't replicate this. Can you still do so?

**Comment by boffbowsh** [comment] 2015-09-23 07:46
It's still coming from whitehall-admin but on the new domain.

**Comment by fofr** [comment] 2015-09-29 10:21
I'm guessing this was probably caused by https://github.gds/gds/puppet/pull/3312

**Comment by alexmuller** [comment] 2015-09-29 10:23
I think that's what @bradwright's thought at the time was, yep.

**Comment by elliotcm** [comment] 2016-03-04 15:45
@alexmuller This seems to still be the case, is this something we're still looking into?

**Comment by fofr** [comment] 2016-03-04 22:47
I think @boffbowsh did a fix for this, items probably need republishing.

**Comment by boffbowsh** [comment] 2016-03-07 08:58
Tried republishing this, it's still not working. Will add it to our backlog

**Comment by elliotcm** [comment] 2016-03-07 09:08
OK.

**Closed by elliotcm** 2016-03-07 09:08 UTC

**Comment by alexmuller** [comment] 2016-03-15 09:41
Just to be very clear (because I wasn't when I wrote this up originally), I think this bug is quite important. It means if we take down the backend (eg for scheduled maintenance) the frontend starts looking bad.

**Comment by boffbowsh** [comment] 2016-03-15 09:47
It's tracked here https://trello.com/c/F1HVGnkn/480-csv-previews-in-whitehall-using-incorrect-asset-host
